# Generated by Django 5.0.2 on 2024-02-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='created_by',
        ),
    ]
