# Generated by Django 5.0.2 on 2024-02-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_fileupload_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('U', 'Uploaded'), ('Q', 'Queued'), ('P', 'Processing'), ('F', 'Finished'), ('E', 'Error')], default='U', max_length=1),
        ),
    ]
